# Attempt to predict Zmix from DOC
# SRC 2021-12-31

rm(list = ls())
graphics.off()

# Data generated by Model_g440_V0_2018-02-23.R
# Save index of square root of g440, which is approximately normally distributed, and 
# corrected estimate of g440 in the same units
#save(Dall,file='AllData+g440index.Rdata')
#
# Dall is the original merged data frame including estimated g440
# HDall is a subset of the original data frame including Hbird
# save(Dall,HDall,file='AllData+HBird.Rdata')
load(file='AllData+HBird.Rdata')
print('Lake numbers are alphabetic; Paul is 3, Pete is 4, Tuesday is 5',quote=F)
print('   except Hummingbird is 8',quote=F)
load('AllData+HBird.Rdata')
print(HDall[1,])
print('',quote=F)
#
ulake = unique(HDall$LID)
nlake = length(ulake)
print(c('lakes:  ',ulake),quote=F)
#
uyear = unique(HDall$Year)
nyear = length(uyear)
print(c('years',uyear),quote=F)
# 
uDoYall = unique(HDall$DoY)
print(c('DoY',uDoYall),quote=F)
# 
uZt = unique(HDall$Ztherm)
print(c('Ztherms',sort(uZt)),quote=F)

# Extinction coefficients
eps0 <- 0.0213  # Light extinction by pure water, m-1
epsDOC = 0.0514  # DOC light extinction coef, m2 g-1
epsP <- 0.0177   # Phytoplankton chlorophyll, m2 (mg chl)-1

# Useful DoY
June15 = 166
July1 = 182
July15 = 196
Aug15 = 227

HDall0 = na.omit(HDall)
rm(HDall)
HDall = subset(HDall0,subset=(DoY>=July15 & DoY<=Aug15))

# Add lake areas (ha)
HDall$area = 25.9
HDall$area = ifelse(HDall$LID==2,2.3,HDall$area)
HDall$area = ifelse(HDall$LID==3,1.7,HDall$area)
HDall$area = ifelse(HDall$LID==4,2.7,HDall$area)
HDall$area = ifelse(HDall$LID==5,0.9,HDall$area)
HDall$area = ifelse(HDall$LID==6,1.9,HDall$area)
HDall$area = ifelse(HDall$LID==7,3.4,HDall$area)
HDall$area = ifelse(HDall$LID==8,0.76,HDall$area)

# Add other variates
HDall$squarea = sqrt(HDall$area*1.e4/pi)
HDall$IDOC = exp(-epsDOC*HDall$DOC) # light absorbance by DOC

print(c('dimensions of data for all dates ',dim(HDall)),quote=F)

# Calculate means for lake & year combinations
ulake = unique(HDall$LID)
nlake = length(ulake)
print(c('lakes:  ',ulake),quote=F)
#
uyear = unique(HDall$Year)
nyear = length(uyear)
print(c('N years',nyear),quote=F)
# 
# Make a matrix for all the lake years; discard missing lake years at the end
lymax = nlake*nyear
LYmat = matrix(-1,nr=lymax,nc = 8)
count = 1 # row counter
for(i in 1:nlake){ 
  for(j in 1:nyear) {
    iL = ulake[i]
    iY = uyear[j]
    sub0 = subset(HDall,subset=(HDall$LID == iL & HDall$Year == iY))
    LYmat[count,1] = iL
    LYmat[count,2] = iY
    LYmat[count,3] = mean(sub0$squarea)
    LYmat[count,4] = mean(sub0$Ztherm)
    LYmat[count,5] = mean(sub0$T.epi)
    LYmat[count,6] = mean(sub0$DOC)
    LYmat[count,7] = mean(sub0$PLoad)
    LYmat[count,8] = length(sub0$LID)
    count = count+1
  }
}

print('dimensions of all the data',quote=F)
print(dim(HDall),quote=F)
LYall = as.data.frame(na.omit(LYmat))
colnames(LYall) = c('LID','Year','Squarea','Ztherm','T.epi','DOC','PLoad','Ndoy')
print('dimensions of available lake-years',quote=F)
print(dim(LYall),quote=F)
print(LYall[1,])

# Use lake-years to predict Ztherm
reg1 = lm(LYall$Ztherm ~ LYall$Squarea + LYall$DOC + LYall$PLoad )
print(summary(reg1))

er = reg1$residuals
yhat = reg1$fitted.values
# plot residuals
windows(width=12,height=8)
par(mfrow=c(2,3),mar=c(4,4.5,2,2)+0.1,cex.axis=1.8,cex.lab=1.8,cex.main=1.8)
qqnorm(er,pch=19,cex=0.8,main='A. Normal Probability Plot')
qqline(er,col='blue',lwd=2)
plot(LYall$Ztherm,yhat,type='p',pch=3,cex=0.8,xlab='Ztherm. m',
     ylab='Predicted Ztherm, m',main='B. Observations X Predictions')
points(LYall$Ztherm,LYall$Ztherm,type='l',lwd=2,col='blue')
plot(yhat,er,type='p',pch=3,cex=0.8,xlab='Predicted Ztherm, m',
     ylab='residual, m',main='C. Residuals X Predictions')
abline(h=0,lty=2,lwd=2,col='blue')
plot(LYall$DOC,er,type='p',pch=3,cex=0.8,xlab='DOC',ylab='residual, m'
     ,main='D. Residuals X DOC')
abline(h=0,lty=2,lwd=2,col='blue')
plot(LYall$Squarea,er,type='p',pch=3,cex=0.8,xlab='sqrt(area)',
     ylab='residual, m',main='E. Residuals X Fetch')
abline(h=0,lty=2,lwd=2,col='blue')
plot(LYall$PLoad,er,type='p',pch=3,cex=0.8,xlab='sqrt(area)',
     ylab='residual, m',main='F. Residuals x P Load')
abline(h=0,lty=2,lwd=2,col='blue')

# corrected s.e. of lake area effect
sreg1 = summary(reg1)
se.area = sreg1$coefficients[2,2]
se.corr = se.area*(sqrt(86)/sqrt(8)) # increase s.e. due to number of lakes
t.area = reg1$coefficients[2]/se.corr
print('s.e., corrected s.e., and t for lake area effect',quote=F)
print(c(se.area,se.corr,t.area),quote=F)
pt.area = pt(t.area,7,lower.tail=F)
print(c('tail probability ',pt.area),quote=F)

save(HDall,LYall,reg1,file='ZmixModel_LakeYears_Hbird.Rdata')

